package com.example.Vinayaga.mapper;

import com.example.Vinayaga.dto.request.CreateTransactionRequest;
import com.example.Vinayaga.dto.response.ReportTransactionResponse;
import com.example.Vinayaga.dto.response.TransactionResponse;
import com.example.Vinayaga.entity.Transaction;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface TransactionMapper {

    // CreateTransactionRequest → Transaction
    // Ignore ID and timestamp (generated by DB)
    // Ignore project and category — service fetches and sets them after mapping
    @Mapping(target = "transactionId", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "project", ignore = true)
    @Mapping(target = "category", ignore = true)
    Transaction toEntity(CreateTransactionRequest request);

    // Transaction → TransactionResponse
    // Flatten nested project and category relationship fields
    @Mapping(source = "project.projectId", target = "projectId")
    @Mapping(source = "project.projectName", target = "projectName")
    @Mapping(source = "category.categoryId", target = "categoryId")
    @Mapping(source = "category.categoryName", target = "categoryName")
    @Mapping(source = "category.categoryType", target = "categoryType")
    TransactionResponse toResponse(Transaction transaction);

    // Transaction → list of TransactionResponse
    List<TransactionResponse> toResponseList(List<Transaction> transactions);

    // Transaction → ReportTransactionResponse (slim view used in reports)
    @Mapping(source = "project.projectId", target = "projectId")
    @Mapping(source = "project.projectName", target = "projectName")
    @Mapping(source = "category.categoryName", target = "categoryName")
    @Mapping(source = "category.categoryType", target = "categoryType")
    ReportTransactionResponse toReportResponse(Transaction transaction);

    // Transaction → list of ReportTransactionResponse
    List<ReportTransactionResponse> toReportResponseList(List<Transaction> transactions);
}
